# Generated by Django 3.1.1 on 2020-09-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200915_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slugf',
            new_name='slug',
        ),
    ]
